spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GTI619
  thymeleaf:
    cache: false
server:
  port: 8080
  session:
    timeout: 60
#  ssl:
#   key-store: classpath:keystore.p12
#   key-password: secret
#   key-alias: hs
#   key-store-type: PKCS12
#   trust-store-password: secret
#   enabled: true
logging:
  level: DEBUG

