spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GTI619
  thymeleaf:
    cache: false
server:
  port: 8080
  session:
    timeout: 60
#  ssl:
#   key-store: classpath:keystore.jks
#   key-password: secret
#   key-alias: tomcat
#   key-store-type: PKCS12
logging:
  level: security

